### ISSUE TITLE
Missing Python Scripts in libexec 

### ISSUE THREAD

**Issue by DheerajCidda** [nsfcac/Nagios-Redfish-API-Integration#1]
The libexec file consists of the .sh scripts rather than .py scripts. This in turn throws and error in the nagios interface saying "(No output on stdout) stderr: execvp(/usr/local/nagios/libexec/....py ...) failed. errno is 2: No such file or directory" for all the services.

**Comment by DheerajCidda** [comment]
The problem is with the nagnodeconfig.py. When we run it, the hosts.cfg file is as follows:
```
define service{
	use	local-service
	host_name	Compute1
	service_description	check bmc health
	check_command	check-bmc-health
	}
```
Here the check_command is "**check-bmc-health**". In the commands.cfg file the command definition for that check_command is: 
```
define command{
        command_name    check-cpu-health
        command_line    $USER1$/check_cpu_health.py -H $HOSTADDRESS$
        }
```
With this we are missing the .py files in the libexec (i.e., Redfish-plugins), and also and extra service is being generated in i.e., "**check-storage-health**" which doesn't include the check_storage.sh

The following changes are required for the nagnodeconfig.py file
1. update `file.write("\ncheck_command\tcheck-bmc-health")
` to` file.write("\ncheck_command\tcheck-bmc")` for all the services (i.e., removing the word health at the end of each check_command)
2. Delete the following code 
```
# Storage Check
        file.write("\ndefine service{") 
        file.write("\n\tuse\tlocal-service")
        file.write("\n\thost_name\t"+name)
        file.write("\nservice_description\tcheck storage health")
        file.write("\ncheck_command\tcheck-storage-health")
        file.write("\n\t}")
```
3. Add the below code for the Check Fans Health
```
# Check Fans
        file.write("\ndefine service{") 
        file.write("\n\tuse\tlocal-service")
        file.write("\n\thost_name\t"+name)
        file.write("\nservice_description\tcheck fan health")
        file.write("\ncheck_command\tcheck-fans")
        file.write("\n\t}")

```

**Comment by alansill** [comment]
Pull request please!
